/**
 * Generated by orval 🍺
 * Do not edit manually.
 * trastienda API
 * Inventory and sales management for small retail.
 * OpenAPI spec version: 0.0.0
 */

export type GetHealth200Status = typeof GetHealth200Status[keyof typeof GetHealth200Status];


export const GetHealth200Status = {
  ok: 'ok',
} as const;
