/**
 * Generated by orval 🍺
 * Do not edit manually.
 * trastienda API
 * Inventory and sales management for small retail.
 * OpenAPI spec version: 0.0.0
 */
import type { GetHealth200Status } from './getHealth200Status';

export type GetHealth200 = {
  status: GetHealth200Status;
};
