/**
 * Generated by orval 🍺
 * Do not edit manually.
 * trastienda API
 * Inventory and sales management for small retail.
 */
import type { GetLivez200Status } from './getLivez200Status';

export type GetLivez200 = {
  status: GetLivez200Status;
};
