/**
 * Generated by orval 🍺
 * Do not edit manually.
 * trastienda API
 * Inventory and sales management for small retail.
 */

export type GetLivez200Status = typeof GetLivez200Status[keyof typeof GetLivez200Status];


export const GetLivez200Status = {
  ok: 'ok',
} as const;
