/**
 * Generated by orval 🍺
 * Do not edit manually.
 * trastienda API
 * Inventory and sales management for small retail.
 * OpenAPI spec version: 0.0.0
 */
import type { GetReadyz200Status } from './getReadyz200Status';

export type GetReadyz200 = {
  status: GetReadyz200Status;
};
