/**
 * Generated by orval 🍺
 * Do not edit manually.
 * trastienda API
 * Inventory and sales management for small retail.
 * OpenAPI spec version: 0.0.0
 */

export * from './getHealth200';
export * from './getHealth200Status';
