import { defineConfig } from 'orval';

export default defineConfig({
  api: {
    input: '../api/openapi.json',
    output: {
      // wipes src/app/core/api/ on every run: nothing hand-written goes there
      clean: true,
      client: 'angular',
      mode: 'tags-split',
      override: {
        // httpResource helpers for reads, injectable services for writes (ADR-0007)
        angular: { retrievalClient: 'both' },
        // orval's default header minus `OpenAPI spec version`: release-please bumps
        // info.version without running codegen, so that line made every release PR
        // fail the drift check
        header: info => [
          'Generated by orval 🍺',
          'Do not edit manually.',
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
        ],
      },
      schemas: 'src/app/core/api/model',
      // a directory, not a file: in tags-split every file is named after its tag
      target: 'src/app/core/api',
    },
  },
});
