/**
 * Generated by orval 🍺
 * Do not edit manually.
 * trastienda API
 * Inventory and sales management for small retail.
 * OpenAPI spec version: 0.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetLivez200,
  GetMe200,
  GetReadyz200
} from '../model';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable({ providedIn: 'root' })
export class SystemService {
  private readonly http = inject(HttpClient);
/**
 * @summary Liveness probe
 */
 getLivez<TData = GetLivez200>( options?: HttpClientBodyOptions): Observable<TData>;
 getLivez<TData = GetLivez200>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getLivez<TData = GetLivez200>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getLivez<TData = GetLivez200>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/livez`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/livez`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/livez`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary Readiness probe
 */
 getReadyz<TData = GetReadyz200>( options?: HttpClientBodyOptions): Observable<TData>;
 getReadyz<TData = GetReadyz200>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getReadyz<TData = GetReadyz200>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getReadyz<TData = GetReadyz200>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/readyz`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/readyz`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/readyz`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
/**
 * @summary The authenticated caller
 */
 getMe<TData = GetMe200>( options?: HttpClientBodyOptions): Observable<TData>;
 getMe<TData = GetMe200>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getMe<TData = GetMe200>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getMe<TData = GetMe200>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

export type GetLivezClientResult = NonNullable<GetLivez200>
export type GetReadyzClientResult = NonNullable<GetReadyz200>
export type GetMeClientResult = NonNullable<GetMe200>
